DROP TABLE IF EXISTS Student_TBL;
 
CREATE TABLE Student_TBL  (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  contact_no VARCHAR(250) DEFAULT NULL,
  father_name VARCHAR(250) DEFAULT NULL,
  mother_name VARCHAR(250) DEFAULT NULL,
  address VARCHAR(250) DEFAULT NULL
);